// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_j1nCtQ2PITI-iphMKcfNDKsuxi6TPno',
    appId: '1:271150833569:web:9a8ec664e5959bd84e75e0',
    messagingSenderId: '271150833569',
    projectId: 'yellowclassauth',
    authDomain: 'yellowclassauth.firebaseapp.com',
    storageBucket: 'yellowclassauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZxbEtKa9qiP18nBs-cMpxmFLw4t0PWg',
    appId: '1:271150833569:android:bb890395aedf52aa4e75e0',
    messagingSenderId: '271150833569',
    projectId: 'yellowclassauth',
    storageBucket: 'yellowclassauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnihxZcRwAHM-WoO49VJ1bx0evNKqMRs',
    appId: '1:271150833569:ios:c3aa48092012ebe04e75e0',
    messagingSenderId: '271150833569',
    projectId: 'yellowclassauth',
    storageBucket: 'yellowclassauth.appspot.com',
    iosClientId: '271150833569-p25g5nlddedjeufc6covsl95hva2ub71.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCnihxZcRwAHM-WoO49VJ1bx0evNKqMRs',
    appId: '1:271150833569:ios:c3aa48092012ebe04e75e0',
    messagingSenderId: '271150833569',
    projectId: 'yellowclassauth',
    storageBucket: 'yellowclassauth.appspot.com',
    iosClientId: '271150833569-p25g5nlddedjeufc6covsl95hva2ub71.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsApp',
  );
}
